import { HskItem, HsExplanatoryItem, HsOpinionItem } from '../types';

export const HSK_TARIFF_DATA: HskItem[] = [
  {
    hskCode: '8517.13.0000',
    pureCode: '8517130000',
    nameKo: '스마트폰 (셀룰러 망이나 그 밖의 무선 망용 전화기)',
    nameEn: 'Smartphones for cellular networks or for other wireless networks',
    generalRate: '0%',
    agreementRate: '0% (ITA / WTO)',
    unit1: 'u',
    unit2: 'kg',
    remarks: '정보기술협정(ITA) 무세 품목, 관세율표 제85류 관세통계통합분류표',
  },
  {
    hskCode: '8517.62.6080',
    pureCode: '8517626080',
    nameKo: '무선 데이터 통신용 기기 (블루투스, Wi-Fi 모듈 포함)',
    nameEn: 'Machines for the reception, conversion and transmission of voice, images or other data',
    generalRate: '0%',
    agreementRate: '0% (ITA)',
    unit1: 'u',
    unit2: 'kg',
    remarks: '무선통신 모바일 트랜시버, 음성/데이터 전송 중계장치',
  },
  {
    hskCode: '8471.30.0000',
    pureCode: '8471300000',
    nameKo: '휴대용 자동데이터처리기기 (중량 10kg 이하, 노트북/태블릿)',
    nameEn: 'Portable automatic data processing machines, weighing not more than 10 kg',
    generalRate: '0%',
    agreementRate: '0% (ITA / WTO)',
    unit1: 'u',
    unit2: 'kg',
    remarks: '노트북, 태블릿 PC 및 키보드/디스플레이 일체형 컴퓨터',
  },
  {
    hskCode: '8471.50.1000',
    pureCode: '8471501000',
    nameKo: '디지털 중앙처리장치 (AI 컴퓨팅 서버 및 가속기 포함)',
    nameEn: 'Digital processing units (including AI computing servers & accelerators)',
    generalRate: '0%',
    agreementRate: '0% (ITA)',
    unit1: 'u',
    unit2: 'kg',
    remarks: '고성능 GPU/NPU 탑재 서버 및 중앙처리 모듈',
  },
  {
    hskCode: '8542.31.1000',
    pureCode: '8542311000',
    nameKo: '프로세서와 콘트롤러 (모놀리식 집적회로, 메모리 결합형)',
    nameEn: 'Processors and controllers, whether or not combined with memories (Monolithic ICs)',
    generalRate: '0%',
    agreementRate: '0% (ITA)',
    unit1: 'u',
    unit2: 'g',
    remarks: 'AP, CPU, NPU 및 SoC 반도체 집적회로',
  },
  {
    hskCode: '8542.32.1000',
    pureCode: '8542321000',
    nameKo: '메모리 반도체 (DRAM 및 HBM 고대역폭 메모리)',
    nameEn: 'Memories (DRAM and High Bandwidth Memory - HBM)',
    generalRate: '0%',
    agreementRate: '0% (ITA)',
    unit1: 'u',
    unit2: 'g',
    remarks: '차세대 HBM3E 및 LPDDR5X 반도체 소자',
  },
  {
    hskCode: '8542.32.2000',
    pureCode: '8542322000',
    nameKo: '플래시 메모리 (NAND Flash 메모리 모듈)',
    nameEn: 'Flash memories (NAND Flash Memory modules)',
    generalRate: '0%',
    agreementRate: '0% (ITA)',
    unit1: 'u',
    unit2: 'g',
    remarks: 'SSD 및 차세대 낸드플래시 메모리 저장소자',
  },
  {
    hskCode: '8703.80.1000',
    pureCode: '8703801000',
    nameKo: '구동용 전동기만을 탑재한 전기승용자동차 (EV)',
    nameEn: 'Motor cars principally designed for transport of persons, only with electric motor',
    generalRate: '8%',
    agreementRate: '0% (한-미 / 한-EU FTA)',
    unit1: 'u',
    unit2: 'kg',
    remarks: '배터리 전기자동차 (BEV), 환경친화적 자동차 관세혜택',
  },
  {
    hskCode: '8707.10.0000',
    pureCode: '8707100000',
    nameKo: '승용자동차의 차체 (운전대를 포함한 것을 포함한다)',
    nameEn: 'Bodies (including cabs), for the motor vehicles of heading 87.03',
    generalRate: '8%',
    agreementRate: '0% (FTA)',
    unit1: 'u',
    unit2: 'kg',
    remarks: '자동차 제조 및 정비용 차체 조립체',
  },
  {
    hskCode: '8507.60.3000',
    pureCode: '8507603000',
    nameKo: '리튬이온 축전지 (전기차용 배터리 팩 및 ESS용 모듈)',
    nameEn: 'Lithium-ion accumulators (for Electric Vehicles & Energy Storage Systems)',
    generalRate: '8%',
    agreementRate: '0% (ITA / FTA)',
    unit1: 'u',
    unit2: 'kg',
    remarks: 'EV 이차전지 모듈, NCM/LFP 배터리 팩',
  },
  {
    hskCode: '9031.80.9090',
    pureCode: '9031809090',
    nameKo: '반도체 검사용 광학 measurement 및 자동측정 기기',
    nameEn: 'Other measuring or checking instruments, appliances and machines',
    generalRate: '0%',
    agreementRate: '0% (ITA)',
    unit1: 'u',
    unit2: 'kg',
    remarks: '반도체 웨이퍼 결함 검사 및 정밀 계측기',
  },
  {
    hskCode: '3002.15.0000',
    pureCode: '3002150000',
    nameKo: '면역물품 (단일클론항체, 바이오시밀러 의약품)',
    nameEn: 'Immunological products, put up in measured doses (Monoclonal Antibodies)',
    generalRate: '0%',
    agreementRate: '0% (Pharma Agreement)',
    unit1: 'kg',
    unit2: 'u',
    remarks: '바이오 의약품 및 항체 치료제 (무세협정)',
  },
  {
    hskCode: '2710.12.1000',
    pureCode: '2710121000',
    nameKo: '휘발유 (자동차용 무연 휘발유)',
    nameEn: 'Motor spirit (Unleaded gasoline for automobiles)',
    generalRate: '3%',
    agreementRate: '3% (기본관세)',
    unit1: 'ℓ',
    unit2: 'kg',
    remarks: '석유 및 석유비투멘유, 할당관세 적용 대상',
  },
  {
    hskCode: '3901.10.0000',
    pureCode: '3901100000',
    nameKo: '폴리에틸렌 (비중이 0.94 미만인 것, LDPE/LLDPE)',
    nameEn: 'Polyethylene having a specific gravity of less than 0.94',
    generalRate: '6.5%',
    agreementRate: '0% (FTA)',
    unit1: 'kg',
    unit2: '-',
    remarks: '석유화학 합성수지 원료 (초기형태)',
  },
  {
    hskCode: '0901.21.0000',
    pureCode: '0901210000',
    nameKo: '볶은 카페인 미제거 원두커피',
    nameEn: 'Roasted coffee, not decaffeinated',
    generalRate: '8%',
    agreementRate: '0% (한-colombia FTA 등)',
    unit1: 'kg',
    unit2: '-',
    remarks: '커피 원두 및 분쇄 가공 원두',
  },
];

export const HS_EXPLANATORY_DATA: HsExplanatoryItem[] = [
  {
    category: '별표1 (HS해설서)',
    sectionChapter: '제16부 제85류',
    hsHeading: '8517',
    titleKo: '전화기(셀룰러 망이나 그 밖의 무선 망용 전화기를 포함한다)와 음성ㆍ이미지나 그 밖의 데이터를 송신ㆍ수신하기 위한 그 밖의 기기',
    titleEn: 'Telephone sets, including smartphones and other telephones for cellular networks or for other wireless networks; other apparatus for the transmission or reception of voice, images or other data',
    scopeContent: '본 호는 지선망/무선망을 통하여 음성, 영상, 데이터 등의 정보를 전송 또는 수용하는 기기를 포함함. 셀룰러 스마트폰, 무선 통신용 베이스스테이션, 루터(Router), 스위칭 기기, 블루투스/Wi-Fi 트랜시버 모듈을 포함함.',
    guideline: 'WCO HS 해설서 지침에 따라 스마트워치 중 독립적 전화통화/데이터 송수신 기능이 주된 기능을 구성하는 경우 제8517호로 분류하며, 단순 계측 중심 기기는 제9031호 또는 제9102호와 구별함.',
  },
  {
    category: '별표1 (HS해설서)',
    sectionChapter: '제16부 제84류',
    hsHeading: '8471',
    titleKo: '자동데이터처리매신과 그 단위기기ㆍ생체인식용/자기식/광학식 독자기와 데이터를 데이터매체에 부호화된 형태로 전기식으로 처리하는 매신',
    titleEn: 'Automatic data processing machines and units thereof; magnetic or optical readers, machines for transcribing data onto data media in coded form and machines for processing such data',
    scopeContent: '본 호는 중앙처리장치(CPU), 입력장치(키보드/마우스), 출력장치(디스플레이)를 갖추고 사용자의 프로그램에 따라 자유롭게 산술/논리 연산을 수행할 수 있는 컴퓨터 시스템을 포함함.',
    guideline: 'AI 가속기 및 GPU 컴퓨팅 서버의 경우 자동데이터처리용 단위기기(제8471.50호)로 분류하며, 단순 영상 출력용 그래픽카드는 본 호에 분류됨.',
  },
  {
    category: '별표1 (HS해설서)',
    sectionChapter: '제16부 제85류',
    hsHeading: '8542',
    titleKo: '전자집적회로 (Electronic Integrated Circuits)',
    titleEn: 'Electronic integrated circuits',
    scopeContent: '본 호는 모놀리식 집적회로, 하이브리드 집적회로, 다중칩 집적회로(MCO) 및 실리콘 기반 모듈을 포함함. 프로세서, 컨트롤러, 메모리(DRAM, SRAM, NAND Flash, HBM), 앰프 등을 분류함.',
    guideline: 'HBM(고대역폭 메모리) 및 실리콘 관통비아(TSV) 기술이 적용된 3차원 적층 메모리는 모놀리식/다중칩 집적회로의 정의에 부합하므로 제8542.32호로 정밀 분류함.',
  },
  {
    category: '별표1 (HS해설서)',
    sectionChapter: '제17부 제87류',
    hsHeading: '8703',
    titleKo: '주로 사람을 수송하도록 설계된 승용자동차와 그 밖의 차량(스테이션왜건과 구급차를 포함한다)',
    titleEn: 'Motor cars and other motor vehicles principally designed for the transport of persons (other than those of heading 87.02), including station wagons and racing cars',
    scopeContent: '내연기관 자동차, 하이브리드 자동차(HEV/PHEV), 배터리 전기자동차(BEV), 수소연료전지차(FCEV)를 포함한 사람 수송용 승용차량을 모두 통괄함.',
    guideline: '2022/2026 HS 개정에 따라 구동용 전동기만을 탑재한 순수 전기자동차(BEV)는 소호 제8703.80호에 전용 분류됨.',
  },
  {
    category: '별표1 (HS해설서)',
    sectionChapter: '제16부 제85류',
    hsHeading: '8507',
    titleKo: '축전지 (선폐기물을 포함하며, 사각형이나 그 밖의 모양인지에 상관없다)',
    titleEn: 'Electric accumulators, including separators therefor, whether or not rectangular (including square)',
    scopeContent: '납축전지, 니켈-카드뮴 축전지, 니켈-수소 축전지, 리튬이온 축전지 및 이차전지 팩/모듈을 포함함. 셀 보호회로(BMS) 탑재 여부와 관계없이 분류함.',
    guideline: '전기차용 이차전지 모듈 및 ESS(에너지저장장치)용 리튬이온 축전지는 제8507.60호로 분류하며, 단순 전력변환 인버터가 결합된 통합장치는 기능에 따라 재검토함.',
  },
  {
    category: '별표1 (HS해설서)',
    sectionChapter: '제18부 제90류',
    hsHeading: '9031',
    titleKo: '그 밖의 측정용이나 검사용 기기(이 류에 따로 분류되지 않은 것으로 한정한다)',
    titleEn: 'Measuring or checking instruments, appliances and machines, not specified or included elsewhere in this Chapter',
    scopeContent: '기계적, 광학적, 전기적 방법을 사용하여 치수, 표면 결함, 반도체 웨이퍼 패턴, 변형률 등을 계측/검사하는 자동화 전문 장비를 분류함.',
    guideline: '반도체 제조 공정 중 웨이퍼 가공 상태나 형상을 광학 레이저로 검사하는 에이전트 장비는 제9031.80호에 분류됨.',
  },
  {
    category: '별표1 (HS해설서)',
    sectionChapter: '제6부 제30류',
    hsHeading: '3002',
    titleKo: '사람의 피, 치료용ㆍ예방용ㆍ진단용으로 조제한 동물의 피, 면역혈청ㆍ그 밖의 혈액 분획물과 면역물품',
    titleEn: 'Human blood; animal blood prepared for therapeutic, prophylactic or diagnostic uses; antisera, other blood fractions and immunological products',
    scopeContent: '백신, 면역혈청, 단일클론항체(MAB), 바이오시밀러, 유전자치료제 및 세포치료제를 포함하는 면역 의약품 부류.',
    guideline: '유전자재조합 기술로 생산된 단일클론항체 제제는 제3002.15호에 특정 분류함.',
  },
];

export const HS_OPINION_DATA: HsOpinionItem[] = [
  {
    category: '별표2 (HS품목분류의견서)',
    opinionNo: 'HS-OP-2026-8517-01',
    subheading: '8517.62',
    itemName: '무선 가상현실(VR/AR) 헤드셋 (독립형 컴퓨팅 & 무선 통신 기능 탑재)',
    opinionText: 'WCO HS 위원회 제72차 총회 결정: 본 물품은 독립된 CPU/GPU와 Wi-Fi/블루투스 무선 데이터 송수신 장치를 탑재하여 무선 데이터 통신 및 영상 처리를 수행하므로 제8517.62호로 분류함.',
    rationale: '통신망을 통한 무선 데이터의 송수신 기능이 물품의 본질적 특성을 구성하며, 단순 모니터(제8528호)나 기타 통신장치보다 제8517.62호의 소호 해설에 가장 부합함.',
    remarks: '관세청 품목분류 적용기준 고시 별표2 제8517호 수록 판례 및 WCO 결정 사례',
  },
  {
    category: '별표2 (HS품목분류의견서)',
    opinionNo: 'HS-OP-2025-8471-04',
    subheading: '8471.50',
    itemName: 'AI 딥러닝 전용 신경망처리장치(NPU) PCIe 가속 모듈',
    opinionText: '관세청 품목분류위원회 결정: 서버용 확장 슬롯에 착탈되어 인공지능 행렬 연산 및 텐서 처리를 전담 수행하는 하드웨어 가속 모듈은 자동데이터처리용 처리단위기기로 보아 제8471.50호로 분류함.',
    rationale: '관세율표 제16부 주 제3호 및 제8471호 주 제5호 나목에 따라 자율적 연산 처리 기능을 수행하는 중앙처리장치의 보조 단위기기에 해당함.',
    remarks: '기획재정부 고시 관세율표 해석 지침 및 2025년 신규 품목분류 결정사례',
  },
  {
    category: '별표2 (HS품목분류의견서)',
    opinionNo: 'HS-OP-2025-8542-02',
    subheading: '8542.32',
    itemName: 'TSV(실리콘 관통 비아) 기반 적층형 HBM3E 메모리 모듈',
    opinionText: 'WCO HS 위원회 결정: D-RAM 실리콘 다이를 수직 적층하고 최하단에 로직 다이를 통합 결합한 모듈은 전자집적회로(메모리) 제8542.32호로 분류함.',
    rationale: '여러 개의 실리콘 다이가 하나의 패키지 내에 복합 연결되어 있더라도 모놀리식/다중칩 집적회로의 통상적 공정 및 기능적 범주 내에 속하므로 제8542.32호에 정밀 지정함.',
    remarks: '반도체 무세협정(ITA) 적용대상 품목 확인서 및 고시 별표2 수록',
  },
  {
    category: '별표2 (HS품목분류의견서)',
    opinionNo: 'HS-OP-2025-8703-09',
    subheading: '8703.80',
    itemName: '전기모터 구동 및 소형 발전용 가솔린 엔진을 탑재한 주행거리 연장형 전기차(EREV)',
    opinionText: '관세품목분류포털(UNIPASS) 행정해석: 탑재된 내연기관이 바퀴에 동력을 전달하지 않고 전적으로 배터리 충전용 발전기만을 구동하는 경우 소호 제8703.80호(전동자동차)로 분류함.',
    rationale: '차량의 직접 구동력이 100% 전기모터에서 발생하므로 플러그인 하이브리드(제8703.60호)가 아닌 순수 전동기 구동 차량(제8703.80호)으로 확정함.',
    remarks: '2025년 관세청 행정규칙 고시 분류의견서 별표2 개정 수록',
  },
  {
    category: '별표2 (HS품목분류의견서)',
    opinionNo: 'HS-OP-2025-9031-03',
    subheading: '9031.80',
    itemName: 'EUV 반도체 노광 공정용 초정밀 3차원 광학 패턴 검사장치',
    opinionText: 'WCO 분류의견서: 펠리클 및 극자외선 포토마스크의 미세 결함을 3차원 인페로메트리 레이저로 검출하는 시스템은 제9031.80호로 분류함.',
    rationale: '반도체 제조용 전용 기계(제8486호)와 별개로, 제조 공정 중의 품질 측정/검사에 독자적으로 사용되므로 제90류의 광학측정기기 부류로 최종 판단함.',
    remarks: '국가법령정보포털 관세청 행정규칙 고시 별표2 수록',
  },
];
